n4m_selector_cases <- function() list(
  wvc_threshold_select = list(),
  spa_select = list(top_k = 5L),
  wvc_select = list(top_k = 5L, normalize = FALSE),
  stability_select = list(top_k = 5L),
  cars_select = list(n_iterations = 8L, min_features = 3L),
  interval_select = list(interval_width = 3L, step = 1L),
  uve_select = list(noise_features = 12L, noise_seed = 7L),
  t2_select = list(alpha_thresholds = c(0.1, 0.3, 0.5), min_selected = 2L),
  random_frog_select = list(n_iterations = 8L, initial_size = 6L,
    min_size = 2L, max_size = 10L, top_k = 5L, seed = 7L),
  scars_select = list(n_iterations = 8L, min_features = 3L, seed = 7L),
  ga_select = list(n_generations = 5L, population_size = 8L,
    min_features = 2L, max_features = 10L, seed = 7L),
  pso_select = list(n_swarm = 8L, n_iterations = 5L, seed = 7L),
  vissa_select = list(n_iterations = 3L, n_submodels = 8L,
                      ratio_kept = 0.5, seed = 7L),
  shaving_select = list(n_steps = 3L, min_features = 3L),
  bve_select = list(n_steps = 3L, min_features = 3L),
  emcuve_select = list(noise_features = 12L, noise_seed = 7L,
                       n_ensembles = 3L),
  randomization_select = list(n_permutations = 100L,
                              randomization_seed = 7L, alpha = 0.5),
  bipls_select = list(interval_width = 3L, min_intervals = 1L),
  sipls_select = list(interval_width = 3L, combination_size = 2L),
  rep_select = list(n_steps = 3L, min_features = 3L, remove_count = 1L),
  ipw_select = list(n_iterations = 3L, top_k = 5L),
  st_select = list(thresholds = c(0.1, 0.5, 1), min_selected = 2L),
  iriv_select = list(max_rounds = 4L, seed = 7L),
  irf_select = list(n_iterations = 8L, window_size = 3L,
                    initial_intervals = 3L, top_k = 3L, seed = 7L),
  vip_spa_select = list(vip_threshold = 0.3, top_k = 5L))
